# Generated by Django 3.0.5 on 2020-04-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommender', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university_course',
            old_name='min_ielts',
            new_name='academic_reputation_score',
        ),
        migrations.AddField(
            model_name='university_course',
            name='academic_reputation_rank',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='university_course',
            name='acceptance_rate',
            field=models.FloatField(default=0.0, max_length=20),
        ),
        migrations.AddField(
            model_name='university_course',
            name='age',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='university_course',
            name='average_tuition_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='university_course',
            name='campus_setting',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='university_course',
            name='citation_rank',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='university_course',
            name='citation_score',
            field=models.FloatField(default=0.0, max_length=20),
        ),
        migrations.AddField(
            model_name='university_course',
            name='cost_of_living_index',
            field=models.FloatField(default=0.0, max_length=20),
        ),
        migrations.AddField(
            model_name='university_course',
            name='employer_reputation_rank',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='university_course',
            name='employer_reputation_score',
            field=models.FloatField(default=0.0, max_length=20),
        ),
        migrations.AddField(
            model_name='university_course',
            name='faculty_student_rank',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='university_course',
            name='faculty_student_score',
            field=models.FloatField(default=0.0, max_length=20),
        ),
        migrations.AddField(
            model_name='university_course',
            name='field_of_study',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='university_course',
            name='international_faculty_rank',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='university_course',
            name='international_faculty_score',
            field=models.FloatField(default=0.0, max_length=20),
        ),
        migrations.AddField(
            model_name='university_course',
            name='international_student_percentage',
            field=models.FloatField(default=0.0, max_length=20),
        ),
        migrations.AddField(
            model_name='university_course',
            name='international_student_rank',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='university_course',
            name='international_student_score',
            field=models.FloatField(default=0.0, max_length=20),
        ),
        migrations.AddField(
            model_name='university_course',
            name='min_GPA',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='university_course',
            name='min_IELTS',
            field=models.FloatField(default=0.0, max_length=20),
        ),
        migrations.AddField(
            model_name='university_course',
            name='min_TOEFL',
            field=models.FloatField(default=0.0, max_length=20),
        ),
        migrations.AddField(
            model_name='university_course',
            name='offer_airport_pickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='university_course',
            name='offer_work_study_program',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='university_course',
            name='overall_score',
            field=models.FloatField(default=0.0, max_length=20),
        ),
        migrations.AddField(
            model_name='university_course',
            name='population_size',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='university_course',
            name='program_name',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='university_course',
            name='region',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='university_course',
            name='status',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='university_course',
            name='city',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='university_course',
            name='country',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='university_course',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='university_course',
            name='name',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='university_course',
            name='subject',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
