# Generated by Django 3.0.5 on 2020-04-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('University_Course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university_course',
            name='min_ietls',
            field=models.FloatField(default=0.0, max_length=20),
        ),
    ]
