# Generated by Django 3.0.5 on 2020-04-07 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('University_Course', '0002_auto_20200407_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university_course',
            old_name='min_ietls',
            new_name='min_ielts',
        ),
    ]
