# Generated by Django 3.0.5 on 2020-04-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='S',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unset', max_length=50)),
                ('preferred_country', models.CharField(default='unset', max_length=50)),
                ('ietls_score', models.FloatField(default='0.0', max_length=50)),
            ],
        ),
    ]
