# Generated by Django 3.0.5 on 2020-04-07 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='S',
            new_name='Student',
        ),
    ]
