# Generated by Django 3.0.5 on 2020-04-07 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_auto_20200407_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='ietls_score',
            new_name='ielts_score',
        ),
    ]
