# Generated by Django 3.0.5 on 2020-04-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_auto_20200407_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ielts_score',
            field=models.FloatField(default=0.0, max_length=50),
        ),
    ]
